### ISSUE TITLE
Update jdbc driver

### ISSUE THREAD

**Issue by AB-xdev** [xdev-software/xapi-db-postgresql#3]

**Comment by DanielLeinberger** [comment]
According to this [Answer](https://stackoverflow.com/a/68264405) in StackOverflow, the code written for the jdbc driver 9.0 is compatible with the major version 42. 
Therefore, it's possible to use the newest version [42.5.1](https://mvnrepository.com/artifact/org.postgresql/postgresql/42.5.1). 
As far as I can tell, the code doesn't show any problems when upgrading to this version.
